window.FBX_LOCALIZATION = {
  template: "Tank Template",
  uploadCamouflage: "Upload camouflage",
  tilesPerSide: "Tiles per side",
  tileRotation: "Tile rotation",
  modelRotation: "Tank rotation",
  cubemap: "Map",
  enableCubemap: "Enable map lighting",
  cubemapRotationX: "Cubemap rotation X",
  cubemapRotationY: "Cubemap rotation Y",
  cubemapRotationZ: "Cubemap rotation Z",
  cubemapDisabled: "Cubemap disabled.",
  cubemapLoading: "Loading cubemap...",
  cubemapLoaded: "Loaded cubemap: {name}.",
  cubemapLoadError: "Could not load cubemap: {name}.",
  noCubemaps: "No cubemaps configured.",
  modelVerticalPosition: "Model vertical position",
  modelHorizontalPosition: "Model horizontal position",
  cameraFov: "Camera FOV",
  resetView: "Reset Camera",
  frameModel: "Frame model",
  copyCurrentConfig: "Copy current config",
  downloadPng: "Download browser screenshot",
  countdownTitle: "Countdown to August 13, 2026",
  days: "Days",
  hours: "Hours",
  minutes: "Minutes",
  seconds: "Seconds",
  participateHere: "Participate here",
  loading: "Loading...",
  loadingFbx: "Loading FBX",
  loadingPbr: "Loading PBR maps",
  processingPbr: "Processing PBR maps",
  processingCamo: "Processing camouflage",
  loadingCubemapProgress: "Loading map",
  editorInstructions: "",
  viewerInstructions: "Load your 512*512 texture and select your template. Drag the slider to view different variations. Instructional Video: https://youtu.be/-kb414gQ7CY | Thanks to imakamikaze69 for beta test",
  templateAlt: "Template",
  tilesLabel: "Tiles",
  rotationLabel: "Rotation",
  countdownFinished: "The Contest has ended!",
  anisotropicFiltering: "Anisotropic filtering",
  lowAngledTextureQuality: "Warning. Your device does not support the highest graphical settings. Please use a higher end device.",
  squareTextureError: "Texture is {width} x {height}. Select a square image.",
  camouflageLoaded: "Loaded {file}.",
  loadingModel: "Loading FBX and body PBR maps...",
  templateLoaded: "Loaded {template}.",
  configCopied: "Current config copied.",
  configMissing: "One or more configuration files did not load.",
  screenshotPrompt: "Select this browser tab or window in the sharing dialog.",
  screenshotSaved: "Browser screenshot saved.",
  screenshotCancelled: "Screenshot cancelled.",
  screenshotUnsupported: "This browser does not support screen capture.",
  decreaseTiles: "Decrease tiles",
  increaseTiles: "Increase tiles",
  decreaseTileRotation: "Decrease tile rotation",
  increaseTileRotation: "Increase tile rotation",
  decreaseModelRotation: "Decrease model rotation",
  increaseModelRotation: "Increase model rotation"
};
